### ISSUE TITLE
Find text on page not working on Firefox

### ISSUE THREAD

**Issue by loraxle** [loraxle/History-of-Computer-Communications#15]
Find (Ctrl F) in Firefox for Windows is not working for any of the content pages. Chrome has some problems as well. Find in Safari and Chrome for iOS seems to work fine...

**Comment by loraxle** [comment]
It looks like it works in Firefox now, but the search also picks up words in the nav panel. Could we exclude the nav panel from Find on page?

**Comment by thelonegrainger** [comment]
Looks like hiding the nav panel from search results would have a negative effect on SEO

**Comment by loraxle** [comment]
Okay, no worries.

For the interview bio pictures, I'm still getting a broken image or alt
text instead of the image. When I hit reload it appears. Is this happening
for you too?

L

**Comment by loraxle** [comment]
Looks like if I clear cache on the iPad it works. Somehow, I can't seem to
clear the cache on Chrome on the Macbook...

**Comment by loraxle** [comment]
Okay, sorry. Finally got the cache cleared. Must have been hiding some
netlify files on there somewhere... 😂
