### ISSUE TITLE
Home page edits

### ISSUE THREAD

**Issue by loraxle** [loraxle/History-of-Computer-Communications#23]
Need to remove first image of printed book and announcement to the right of the book. Can we replace this with an announcement of the site update?

Welcome! You are viewing the new, updated site. Our old site (link) will still be available until July 1st.

We've been hard at work redesigning "The History of Computer Communications" so that it is easier to navigate on all your devices. We've made some significant improvements, including a new site search engine, a comprehensive navigation menu, as well as some additional primary documents and source materials. We hope you enjoy the new look! We would love to hear your feedback. (link to the contact page...)

**Comment by thelonegrainger** [comment]
@loraxle Assuming we are removing this info from the footer as well?
